# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

fetch_all_vacancies:
  class: FetchAllVacanciesJob
  schedule: every 3 hours

cleanup_old_vacancies:
  class: CleanUpOldVacanciesJob
  args: [ { days_old: 30 } ]
  schedule: every day at 1am

